# Generated by Django 3.2.14 on 2022-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10),
        ),
    ]
