# Generated by Django 3.2.14 on 2022-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_shipping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
