# Generated by Django 3.2.14 on 2022-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
