# Generated by Django 3.2.14 on 2022-11-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_previous_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(
                choices=[
                    ('Received',
                     'Order Received'),
                    ('Processing',
                     'Order Processing'),
                    ('Dispatched',
                     'Order Dispatched'),
                    ('On Hold',
                     'On Hold')],
                default='Received',
                max_length=20),
        ),
        migrations.CreateModel(
            name='InternalOrderNotes',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('notes',
                 models.TextField()),
                ('order',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='checkout.order')),
            ],
        ),
    ]
