# Generated by Django 3.2.14 on 2022-11-19 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20221119_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalordernotes',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
