# Generated by Django 3.2.14 on 2022-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
