# Generated by Django 3.2.14 on 2022-11-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_reason', models.CharField(choices=[('General Support', 'General Support'), ('Order', 'Order'), ('Product Info', 'Product Info'), ('Other', 'Other')], default='General Support', max_length=50)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('pending_reply', models.BooleanField(default=True)),
                ('marked_as_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InternalCommunicationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('related_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_message', to='contact_form.customermessages')),
            ],
        ),
    ]
