# Generated by Django 3.2.14 on 2022-11-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_remove_customermessages_contact_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessages',
            options={'verbose_name_plural': 'Customer Messages'},
        ),
    ]
