# Generated by Django 3.2.14 on 2022-11-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20221022_1615'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='user',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='review_author',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='product_reviewed',
                to='products.allproducts'),
        ),
    ]
