# Generated by Django 3.2.14 on 2022-11-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221112_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
