# Generated by Django 3.2.14 on 2022-11-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221022_1615'),
        ('reviews', '0004_alter_productreviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='product_reviewed',
                to='products.allproducts'),
        ),
    ]
