# Generated by Django 3.2.14 on 2022-10-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('current_rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('accumulative_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('Number_of_ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('stock_level', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('has_sale', models.BooleanField(default=False)),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'All Products',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmatic_name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category Groupings',
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('accessory_type', models.CharField(choices=[('Chargers', 'Chargers'), ('Cases', 'Cases'), ('Tools', 'Tools'), ('Other', 'Other')], default='Chargers', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='BaseLiquids',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('size', models.CharField(choices=[('250', '250ml'), ('500', '500ml'), ('1000', '1000ml')], default='250', max_length=4)),
                ('pg_vg_ratio', models.CharField(choices=[('50/50', '50pg/50vg'), ('70/30', '70pg/30vg'), ('100/0', '100%pg'), ('0/100', '100%vg')], default='50/50', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Base Liquids',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='Batteries',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('battery_type', models.CharField(choices=[('18650', '18650'), ('20700', '20700'), ('21700', '21700')], default='18650', max_length=5)),
                ('capacity', models.CharField(blank=True, max_length=254, null=True)),
                ('discharge_rate', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Batteries',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='DisposableVapes',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('battery_size', models.CharField(blank=True, max_length=254, null=True)),
                ('max_puffs', models.CharField(blank=True, max_length=254, null=True)),
                ('flavour', models.CharField(blank=True, max_length=254, null=True)),
                ('nicotine_strength', models.CharField(choices=[('0', '0mg'), ('10', '10mg'), ('20', '20mg')], default='0', max_length=2)),
                ('liquid_capacity', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Disposable Vapes',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('colour', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mods',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('capacity', models.CharField(blank=True, max_length=254, null=True)),
                ('tank_type', models.CharField(choices=[('Sub-Ohm', 'Sub-Ohm'), ('RDTA', 'RDTA'), ('RTA', 'RTA'), ('Dripper', 'Dripper')], default='Sub-Ohm', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Tanks',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='VapeJuice',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('flavour', models.CharField(blank=True, max_length=254, null=True)),
                ('nicotine_strength', models.CharField(choices=[('0', '0mg'), ('3', '3mg'), ('6', '6mg'), ('12', '12mg'), ('18', '18mg'), ('24', '24mg')], default='0', max_length=2)),
                ('size', models.CharField(choices=[('10', '10ml'), ('30', '30ml'), ('50', '50ml'), ('75', '75ml'), ('100', '100ml')], default='10', max_length=3)),
                ('pg_vg_ratio', models.CharField(choices=[('50/50', '50pg/50vg'), ('70/30', '70pg/30vg'), ('20/80', '20pg/80vg'), ('0/100', '100%vg')], default='50/50', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Vape Juice',
            },
            bases=('products.allproducts',),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorygroupings'),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_products.allproducts_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='PreBuiltCoils',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('coil_type', models.CharField(choices=[('Mesh', 'Mesh'), ('Kanthal', 'Kanthal'), ('Nickel', 'Nickel'), ('Stainless Steel', 'Stainless Steel')], default='Mesh', max_length=15)),
                ('resistance', models.CharField(blank=True, max_length=254, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coils', to='products.tanks')),
            ],
            options={
                'verbose_name_plural': 'Pre-Built Coils',
            },
            bases=('products.allproducts',),
        ),
    ]
