# Generated by Django 3.2.14 on 2022-10-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposablevapes',
            options={'verbose_name_plural': 'Disposable Vapes'},
        ),
    ]
