# Generated by Django 3.2.14 on 2022-10-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorConcentrates',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('size', models.CharField(choices=[('10', '10ml'), ('30', '30ml')], default='10', max_length=3)),
                ('flavour', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Flavor Concentrates',
            },
            bases=('products.allproducts',),
        ),
        migrations.CreateModel(
            name='NicotineShots',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('size', models.CharField(choices=[('10', '10ml')], default='10', max_length=2)),
                ('nicotine_strength', models.CharField(choices=[('18', '18mg'), ('20', '20mg'), ('36', '36mg')], default='18', max_length=2)),
                ('nicotine_type', models.CharField(choices=[('Nicotine', 'Nicotine'), ('Nicotine Salt', 'Nicotine Salt')], default='Nicotine', max_length=13)),
            ],
            options={
                'verbose_name_plural': 'Nicotine',
            },
            bases=('products.allproducts',),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='accessory_type',
            field=models.CharField(choices=[('Wire', 'Wire'), ('Wick', 'Wick'), ('Chargers', 'Chargers'), ('Cases', 'Cases'), ('Tools', 'Tools'), ('Other', 'Other')], default='Chargers', max_length=8),
        ),
    ]
