# Generated by Django 3.2.14 on 2022-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221009_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygroupings',
            old_name='programmatic_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='products/'),
        ),
    ]
