# Generated by Django 3.2.14 on 2022-10-09 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221008_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('colour', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mods',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('capacity', models.CharField(blank=True, max_length=254, null=True)),
                ('tank_type', models.CharField(choices=[('Sub-Ohm', 'Sub-Ohm'), ('RDTA', 'RDTA'), ('RTA', 'RTA'), ('Dripper', 'Dripper')], default='Sub-Ohm', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Tanks',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='VapeJuice',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('flavour', models.CharField(blank=True, max_length=254, null=True)),
                ('nicotine_strength', models.CharField(choices=[('0', '0mg'), ('3', '3mg'), ('6', '6mg'), ('12', '12mg'), ('18', '18mg'), ('24', '24mg')], default='0', max_length=2)),
                ('size', models.CharField(choices=[('10', '10ml'), ('30', '30ml'), ('50', '50ml'), ('75', '75ml'), ('100', '100ml')], default='10', max_length=3)),
                ('pg_vg_ratio', models.CharField(choices=[('50/50', '50pg/50vg'), ('70/30', '70pg/30vg'), ('20/80', '20pg/80vg'), ('0/100', '100%vg')], default='50/50', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Vape Juice',
            },
            bases=('products.product',),
        ),
    ]
