# Generated by Django 3.2.14 on 2022-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221010_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproducts',
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'All Products'},
        ),
        migrations.AddField(
            model_name='allproducts',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=254,
                null=True),
        ),
    ]
