# Generated by Django 3.2.14 on 2022-10-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_disposablevapes_sub_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposablevapes',
            name='sub_class',
        ),
    ]
