# Generated by Django 3.2.14 on 2022-10-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_disposablevapes_sub_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='product_type',
            field=models.CharField(choices=[('accessory', 'Accessory')], default='accessory', max_length=30),
        ),
        migrations.AddField(
            model_name='baseliquids',
            name='product_type',
            field=models.CharField(choices=[('baseliquid', 'Base Liquid')], default='baseliquid', max_length=30),
        ),
        migrations.AddField(
            model_name='batteries',
            name='product_type',
            field=models.CharField(choices=[('battery', 'Battery')], default='battery', max_length=30),
        ),
        migrations.AddField(
            model_name='disposablevapes',
            name='product_type',
            field=models.CharField(choices=[('disposable', 'Disposable')], default='disposable', max_length=30),
        ),
        migrations.AddField(
            model_name='flavorconcentrates',
            name='product_type',
            field=models.CharField(choices=[('concentrate', 'Flavor Concentrate')], default='concentrate', max_length=30),
        ),
        migrations.AddField(
            model_name='mods',
            name='product_type',
            field=models.CharField(choices=[('mod', 'Mod')], default='mod', max_length=30),
        ),
        migrations.AddField(
            model_name='nicotineshots',
            name='product_type',
            field=models.CharField(choices=[('nicotine', 'Nicotine')], default='nicotine', max_length=30),
        ),
        migrations.AddField(
            model_name='prebuiltcoils',
            name='product_type',
            field=models.CharField(choices=[('coil', 'Coil')], default='coil', max_length=30),
        ),
        migrations.AddField(
            model_name='tanks',
            name='product_type',
            field=models.CharField(choices=[('tank', 'Tank')], default='tank', max_length=30),
        ),
        migrations.AddField(
            model_name='vapejuice',
            name='product_type',
            field=models.CharField(choices=[('vapejuice', 'Vape Juice')], default='vapejuice', max_length=30),
        ),
    ]
