# Generated by Django 3.2.14 on 2022-10-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221016_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     choices=[
                         ('tobedefined',
                          'To be defined'),
                         ('disposable',
                          'Disposable'),
                         ('mod',
                          'Mod'),
                         ('tank',
                          'Tank'),
                         ('coil',
                          'Coil'),
                         ('battery',
                          'Battery'),
                         ('vapejuice',
                          'Vape Juice'),
                         ('baseliquid',
                          'Base Liquid'),
                         ('nicotine',
                          'Nicotine'),
                         ('concentrate',
                          'Flavor Concentrate'),
                         ('accessory',
                          'Accessory')],
                     default='tobedefined',
                     max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Sub Category',
            },
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='baseliquids',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='batteries',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='disposablevapes',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='flavorconcentrates',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='nicotineshots',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='prebuiltcoils',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='tanks',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='vapejuice',
            name='product_type',
        ),
        migrations.AddField(
            model_name='allproducts',
            name='sub_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.subcategory'),
        ),
    ]
