# Generated by Django 3.2.14 on 2022-10-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221017_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproducts',
            old_name='Number_of_ratings',
            new_name='number_of_ratings',
        ),
    ]
