# Generated by Django 3.2.14 on 2022-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221022_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='discounted_price',
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=254,
                null=True,
                unique=True),
        ),
    ]
