# Generated by Django 3.2.14 on 2022-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20221119_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='battery_size',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mods',
            name='built_in_battery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mods',
            name='output',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
