# Generated by Django 3.2.14 on 2022-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20221123_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='accumulative_rating',
            field=models.IntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='current_rating',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=6,
                null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='number_of_ratings',
            field=models.IntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True),
        ),
    ]
